# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import gondola.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gondola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='', validators=[gondola.validators.validate_gondola])),
                ('link_to', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('position', models.SmallIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'gondole',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='GondoleRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('label', models.CharField(default='Gondola row', max_length=250)),
                ('position', models.SmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(help_text='Select at least 2 rectangles or 1 rectangle and 2 squares.', to='gondola.Gondola')),
            ],
            options={
                'verbose_name_plural': 'Gondole rows',
                'verbose_name': 'Gondole row',
                'ordering': ['active', 'position', 'modified', 'created'],
            },
        ),
    ]
