# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import gondola.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gondola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gondola',
            name='image',
            field=models.ImageField(upload_to='images/gondole', validators=[gondola.validators.validate_gondola]),
        ),
    ]
